### ISSUE TITLE
Intermediate Catch Event has no Event Definitions?

### ISSUE THREAD

**Issue by chrisw14** [imixs/imixs-bpmn#76]
Hi,
I copied a bpmn file that I don't need start from scratch. After saving I get the following error on all imixs events:
![grafik](https://user-images.githubusercontent.com/29482633/53681617-52c37380-3cec-11e9-8f71-32e3e1f6c875.png)

Is it possible to repair such a file? I tried it three times and always I think when renaming the process name this error occours and I can't undo this. What's wrong if this errors appears?

Thats the file:
[Abwesenheit.zip](https://github.com/imixs/imixs-bpmn/files/2922051/Abwesenheit.zip)

Thank you.

**Comment by rsoika** [comment]
Yes the model file is not valid. If you open it with the XML editor you will see the structural inconsistence. 

line 30
`    <bpmn2:participant id="Participant_1" name="Abwesenheitsantrag" processRef="Process_2">`

and line 168

`  <bpmn2:process id="Process_2" name="Workflow" definitionalCollaborationRef="Collaboration_1" isExecutable="false"/>`

My best recommendation: 
create a new empty BPMN2 file from scratch and than copy your tasks and events from the old one into the new. This is the only way to fix the bpmn2:collaboration and bpmn2:participant structure with the visual representation. It is not a problem from Imixs BPMN. It is the Eclipse BPMN2 Plugin itself. I guess you have done to many copy paste with the origin file....
In my experience you can fix it faster if you start with a new empty file.
